title: CSS (Truscott - UF)
remote_theme: just-the-docs/just-the-docs@v0.5.3
enable_color_mode_toggle: true
color_scheme: dark
baseurl: "/CSS_POS_UF"

# Add this
aux_links:
  "Custom stylesheet":
    - "/assets/css/custom.css"
