title: Computational Social Science (Truscott)
remote_theme: just-the-docs/just-the-docs@v0.5.3

enable_color_mode_toggle: true
color_scheme: uf   # 👈 this matches _sass/color_schemes/uf.scss

baseurl: "/CSS_POS_UF"
