---
title: "Vector Space Model"
subtitle: "POS6933: Computational Social Science"
author: "Truscott (Spring 2026)"
output:
  html_document:
    self_contained: false
    layout: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)

library(ggplot2)
library(dplyr)
library(cowplot)
library(stargazer)
library(doParallel)
library(parallel)
library(snow)
library(tm)
library(quanteda)
library(gutenbergr)
library(stringr)

```

------------------------------------------------------------------------

## Vector Space Model

While a multinomial language model looks at text as a series of words and focuses on how likely each word is to appear, a <b>vector space model</b> treats text as a point in space, letting us measure how similar two texts are based on distance or direction. In essence, MLM is all about word probabilities -- that is, figuring out which words are more likely in a document, whereas VSMs leverage linear algebra to turn text into vectors so we can compare documents based on their overall content, not just exact word counts. 

As you might infer, this forms the key idea behind virtually all similarity-based measures of text: the assumption is that documents sharing similar features -- whether word frequencies (or other vectorized representations...) -- are semantically more alike. 

<b> GSR (Ch. 7) </b> give a great example using the <i>Federalist Papers</i> example to demonstrate how we can use inner products to articulate similar writing styles -- the idea being that greater values represent similar documents (or authorship/writing styles). Using our specific adjusments from the <a href="https://jaketruscott.github.io/CSS_POS_UF/class_6/multinomial_language_model.html#multinomial-language-model">  Multinomial Language Model (Section on MLMs) </a>, we can show how Madison and Hamilton's writing styles are similar than Madison and Jay: 



$$\mathbf{W_{Madison}} \cdot \mathbf{W_{Hamilton}} = (477, 1, 17, 7, 12) \cdot (861, 13, 102, 374, 1) $$
$$= (477 \times 861) + (1 \times 13) + (17 \times 102) + (7 \times 374) + (12 \times 1) $$
$$= 410,697$$



$$\mathbf{W_{Madison}} \cdot \mathbf{W_{Jay}} = (477, 1, 17, 7, 12) \cdot (82, 1, 0, 1, 0, 84) $$
$$= (477 \times 82) + (1 \times 1) + (17 \times 0) + (7 \times 0) + (12 \times 84)$$
$$= 40,123$$

